{{- $name := "postgres-credentials" -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $password := randAlphaNum 20 -}}
{{- if $existing -}}
{{- $password = index $existing.data "POSTGRES_PASSWORD" | b64dec -}}
{{- end }}
# stores sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.database.user }}
  POSTGRES_PASSWORD: {{ $password | quote }}
  POSTGRES_DB: {{ .Values.database.name }}