{{- $name := "grafana-admin" -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $password := randAlphaNum 20 -}}
{{- if $existing -}}
{{- $password = index $existing.data "ADMIN_PASSWORD" | b64dec -}}
{{- end }}
# login for the grafana web interface
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
stringData:
  ADMIN_PASSWORD: {{ $password | quote }}